export const ALL_EMPLYEES_REQUEST = 'ALL_EMPLYEES_REQUEST';
export const ALL_EMPLYEES_SUCCESS = 'ALL_EMPLYEES_SUCCESS';
export const ALL_EMPLYEES_FAIL = 'ALL_EMPLYEES_FAIL';

export const ALL_EMPLYERS_REQUEST = 'ALL_EMPLYERS_REQUEST';
export const ALL_EMPLYERS_SUCCESS = 'ALL_EMPLYERS_SUCCESS';
export const ALL_EMPLYERS_FAIL = 'ALL_EMPLYERS_FAIL';

export const BLOCKED_USERS_REQUEST = 'BLOCKED_USERS_REQUEST';
export const BLOCKED_USERS_SUCCESS = 'BLOCKED_USERS_SUCCESS';
export const BLOCKED_USERS_FAIL = 'BLOCKED_USERS_FAIL';


