export const MY_ROOMS_REQUEST = "MY_ROOMS_REQUEST"
export const MY_ROOMS_SUCCESS = "MY_ROOMS_SUCCESS"
export const MY_ROOMS_FAIL = "MY_ROOMS_FAIL"

export const MY_CHATS_REQUEST = "MY_CHATS_REQUEST"
export const MY_CHATS_SUCCESS = "MY_CHATS_SUCCESS"
export const MY_CHATS_FAIL = "MY_CHATS_FAIL"