export const EMPLOYER_PROFILE_REQUEST = 'EMPLOYER_PROFILE_REQUEST'
export const EMPLOYER_PROFILE_SUCCESS = 'EMPLOYER_PROFILE_SUCCESS'
export const EMPLOYER_PROFILE_FAIL = 'EMPLOYER_PROFILE_FAIL'

export const CHANGE_E_PASSWORD_REQUEST = 'CHANGE_E_PASSWORD_REQUEST'
export const CHANGE_E_PASSWORD_SUCCESS = 'CHANGE_E_PASSWORD_SUCCESS'
export const CHANGE_E_PASSWORD_FAIL = 'CHANGE_E_PASSWORD_FAIL'

