export const EMPLOYEE_PROFILE_REQUEST = 'EMPLOYEE_PROFILE_REQUEST' 
export const EMPLOYEE_PROFILE_SUCCESS = 'EMPLOYEE_PROFILE_SUCCESS' 
export const EMPLOYEE_PROFILE_FAIL = 'EMPLOYEE_PROFILE_FAIL' 

export const EDUCATION_REQUEST = 'EDUCATION_REQUEST'
export const EDUCATION_SUCCESS = 'EDUCATION_SUCCESS'
export const EDUCATION_FAIL = 'EDUCATION_FAIL'

export const BANK_DETAILS_REQUEST = "BANK_DETAILS_REQUEST"
export const BANK_DETAILS_SUCCESS = "BANK_DETAILS_SUCCESS"
export const BANK_DETAILS_FAIL = "BANK_DETAILS_FAIL"

