export const MYJOBS_REQUEST = 'MYJOBS_REQUEST'
export const MYJOBS_SUCCES = 'MYJOBS_SUCCES'
export const MYJOBS_FAIL = 'MYJOBS_FAIL'

export const JOBS_DETAILS_REQUEST = 'JOBS_DETAILS_REQUEST'
export const JOBS_DETAILS_SUCCES = 'JOBS_DETAILS_SUCCES'
export const JOBS_DETAILS_FAIL = 'JOBS_DETAILS_FAIL'

export const  ALL_JOBS_REQUEST = ' ALL_JOBS_REQUEST'
export const  ALL_JOBS_SUCCES = ' ALL_JOBS_SUCCES'
export const ALL_JOBS_FAIL = ' ALL_JOBS_FAIL'

export const JOBS_POST_REQUEST = 'JOBS_POST_REQUEST'
export const JOBS_POST_SUCCES = 'JOBS_POST_SUCCES'
export const JOBS_POST_FAIL = 'JOBS_POST_FAIL'

export const SAVE_JOBS_REQUEST = 'SAVE_JOBS_REQUEST'
export const SAVE_JOBS_SUCCES = 'SAVE_JOBS_SUCCES'
export const SAVE_JOBS_FAIL = 'SAVE_JOBS_FAIL'