export const POST_PROPOSAL_REQUEST = "POST_PROPOSAL_REQUEST";
export const POST_PROPOSAL_SUCCUSS = "POST_PROPOSAL_SUCCUSS";
export const POST_PROPOSAL_FAIL = "POST_PROPOSAL_FAIL";

export const MY_PROPOSAL_REQUEST = "MY_PROPOSAL_REQUEST";
export const MY_PROPOSAL_SUCCUSS = "MY_PROPOSAL_SUCCUSS";
export const MY_PROPOSAL_FAIL = "MY_PROPOSAL_FAIL";
