export const POST_PROPOSAL_REQUEST = "POST_PROPOSAL_REQUEST";
export const POST_PROPOSAL_SUCCUSS = "POST_PROPOSAL_SUCCUSS";
export const POST_PROPOSAL_FAIL = "POST_PROPOSAL_FAIL";

export const MY_PROPOSAL_REQUEST = "MY_PROPOSAL_REQUEST";
export const MY_PROPOSAL_SUCCUSS = "MY_PROPOSAL_SUCCUSS";
export const MY_PROPOSAL_FAIL = "MY_PROPOSAL_FAIL";

export const VIEW_PROPOSAL_REQUEST = "VIEW_PROPOSAL_REQUEST";
export const VIEW_PROPOSAL_SUCCUSS = "VIEW_PROPOSAL_SUCCUSS";
export const VIEW_PROPOSAL_FAIL = "VIEW_PROPOSAL_FAIL";

export const ACCEPT_PROPOSAL_REQUEST = "ACCEPT_PROPOSAL_REQUEST";
export const ACCEPT_PROPOSAL_SUCCUSS = "ACCEPT_PROPOSAL_SUCCUSS";
export const ACCEPT_PROPOSAL_FAIL = "ACCEPT_PROPOSAL_FAIL";