export const ALL_EMPLYEES_REQUEST = 'ALL_EMPLYEES_REQUEST';
export const ALL_EMPLYEES_SUCCESS = 'ALL_EMPLYEES_SUCCESS';
export const ALL_EMPLYEES_FAIL = 'ALL_EMPLYEES_FAIL';

export const ALL_EMPLYERS_REQUEST = 'ALL_EMPLYERS_REQUEST';
export const ALL_EMPLYERS_SUCCESS = 'ALL_EMPLYERS_SUCCESS';
export const ALL_EMPLYERS_FAIL = 'ALL_EMPLYERS_FAIL';

export const BLOCKED_USERS_REQUEST = 'BLOCKED_USERS_REQUEST';
export const BLOCKED_USERS_SUCCESS = 'BLOCKED_USERS_SUCCESS';
export const BLOCKED_USERS_FAIL = 'BLOCKED_USERS_FAIL';


export const ADMIN_PROFILE_REQUEST = 'ADMIN_PROFILE_REQUEST'
export const ADMIN_PROFILE_SUCCESS = 'ADMIN_PROFILE_SUCCESS'
export const ADMIN_PROFILE_FAIL = 'ADMIN_PROFILE_FAIL'


export const ALL_KYC_REQUEST = 'ALL_KYC_REQUEST'
export const ALL_KYC_SUCCESS = 'ALL_KYC_SUCCESS'
export const ALL_KYC_FAIL = 'ALL_KYC_FAIL'

export const KYC_STATUS_REQUEST = 'KYC_STATUS_REQUEST'
export const KYC_STATUS_SUCCESS = 'KYC_STATUS_SUCCESS'
export const KYC_STATUS_FAIL = 'KYC_STATUS_FAIL'

export const ADMIN_CHATS_REQUEST = 'ADMIN_CHATS_REQUEST'
export const ADMIN_CHATS_SUCCESS = 'ADMIN_CHATS_SUCCESS'
export const ADMIN_CHATS_FAIL = 'ADMIN_CHATS_FAIL'