export const MY_ROOMS_REQUEST = "MY_ROOMS_REQUEST"
export const MY_ROOMS_SUCCESS = "MY_ROOMS_SUCCESS"
export const MY_ROOMS_FAIL = "MY_ROOMS_FAIL"

export const MY_CHATS_REQUEST = "MY_CHATS_REQUEST"
export const MY_CHATS_SUCCESS = "MY_CHATS_SUCCESS"
export const MY_CHATS_FAIL = "MY_CHATS_FAIL"


export const CALL_REQUEST = 'CALL_REQUEST'
export const CALL_SUCCESS = 'CALL_SUCCESS'
export const CALL_FAIL = 'CALL_FAIL'

export const HELP_CHAT_REQUEST = 'HELP_CHAT_REQUEST'
export const HELP_CHAT_SUCCESS = 'HELP_CHAT_SUCCESS'
export const HELP_CHAT_FAIL = 'HELP_CHAT_FAIL'