export const EMPLOYER_PROFILE_REQUEST = 'EMPLOYER_PROFILE_REQUEST'
export const EMPLOYER_PROFILE_SUCCESS = 'EMPLOYER_PROFILE_SUCCESS'
export const EMPLOYER_PROFILE_FAIL = 'EMPLOYER_PROFILE_FAIL'

export const CHANGE_E_PASSWORD_REQUEST = 'CHANGE_E_PASSWORD_REQUEST'
export const CHANGE_E_PASSWORD_SUCCESS = 'CHANGE_E_PASSWORD_SUCCESS'
export const CHANGE_E_PASSWORD_FAIL = 'CHANGE_E_PASSWORD_FAIL'


export const FIND_TALENDS_REQUEST = 'FIND_TALENDS_REQUEST'
export const FIND_TALENDS_SUCCESS = 'FIND_TALENDS_SUCCESS'
export const FIND_TALENDS_FAIL = 'FIND_TALENDS_FAIL'


export const DELETE_MESSAGE_REQUEST = 'DELETE_MESSAGE_REQUEST'
export const DELETE_MESSAGE_SUCCESS = 'DELETE_MESSAGE_SUCCESS'
export const DELETE_MESSAGE_FAIL = 'DELETE_MESSAGE_FAIL'
