export const EMPLOYEE_PROFILE_REQUEST = "EMPLOYEE_PROFILE_REQUEST";
export const EMPLOYEE_PROFILE_SUCCESS = "EMPLOYEE_PROFILE_SUCCESS";
export const EMPLOYEE_PROFILE_FAIL = "EMPLOYEE_PROFILE_FAIL";

export const EMPLOYEE_PROFILE_PUBLIC_REQUEST = "EMPLOYEE_PROFILE_REQUEST";
export const EMPLOYEE_PROFILE_PUBLIC_SUCCESS = "EMPLOYEE_PROFILE_SUCCESS";
export const EMPLOYEE_PROFILE_PUBLIC_FAIL = "EMPLOYEE_PROFILE_FAIL";

export const EDUCATION_REQUEST = "EDUCATION_REQUEST";
export const EDUCATION_SUCCESS = "EDUCATION_SUCCESS";
export const EDUCATION_FAIL = "EDUCATION_FAIL";

export const SKILL_N_LANGUAGE_REQUEST = "SKILL_N_LANGUAGE_REQUEST";
export const SKILL_N_LANGUAGE_SUCCESS = "SKILL_N_LANGUAGE_SUCCESS";
export const SKILL_N_LANGUAGE_FAIL = "SKILL_N_LANGUAGE_FAIL";

export const INFO_REQUEST = "INFO_REQUEST";
export const INFO_SUCCESS = "INFO_SUCCESS";
export const INFO_FAIL = "INFO_FAIL";

export const PROFILE_PIC_REQUEST = "PROFILE_PIC_REQUEST";
export const PROFILE_PIC_SUCCESS = "PROFILE_PIC_SUCCESS";
export const PROFILE_PIC_FAIL = "PROFILE_PIC_FAIL";

export const PORTFOLIO_SUCCESS = "PORTFOLIO_SUCCESS";
export const PORTFOLIO_REQUEST = "PORTFOLIO_REQUEST";
export const PORTFOLIO_FAIL = "PORTFOLIO_FAIL";

export const BANK_DETAILS_REQUEST = "BANK_DETAILS_REQUEST";
export const BANK_DETAILS_SUCCESS = "BANK_DETAILS_SUCCESS";
export const BANK_DETAILS_FAIL = "BANK_DETAILS_FAIL";

export const WITHDRAW_REQUEST = "WITHDRAW_REQUEST";
export const WITHDRAW_SUCCESS = "WITHDRAW_SUCCESS";
export const WITHDRAW_FAIL = "WITHDRAW_FAIL";

export const DO_WITHDRAW_REQUEST = "DO_WITHDRAW_REQUEST";
export const DO_WITHDRAW_SUCCESS = "DO_WITHDRAW_SUCCESS";
export const DO_WITHDRAW_FAIL = "DO_WITHDRAW_FAIL";
