export const PURCHASE_hISTORY_REQUEST = "PURCHASE_hISTORY_REQUEST"
export const PURCHASE_hISTORY_SUCCUSS = "PURCHASE_hISTORY_SUCCUSS"
export const PURCHASE_hISTORY_FAIL = "PURCHASE_hISTORY_FAIL"

export const PAYPAL = "ASFMBpteURaWHNhFb5GVWJCIpWgfRGB5M7BIqiFQz5pVJ9sk8RL_uRr_bx_I7QI-7wFP8FNeF9gcPjZg"