export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const OTP_HELPER_FAIL = 'OTP_HELPER';
export const  OTP_HELPER_REQUEST = 'OTP_HELPER_REQUEST'
export const  OTP_HELPER_SUCCESS = 'OTP_HELPER_SUCCESS'

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';


export const  RESET_PASSWORD_REQUEST = ' RESET_PASSWORD_REQUEST';
export const  RESET_PASSWORD_SUCCESS = ' RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = ' RESET_PASSWORD_FAIL';
